export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const STORE_USER_ROLES = "STORE_USER_ROLES";
export const CURRENT_USER_SITE = "CURRENT_USER_SITE";

// MASTER USER
export const GET_ALL_MASTER_USER_INTERNAL = "GET_ALL_MASTER_USER_INTERNAL";
export const GET_MASTER_USER_INTERNAL_BY_ID = "GET_MASTER_USER_INTERNAL_BY_ID"
export const DELETE_MASTER_USER_INTERNAL = "DELETE_MASTER_USER_INTERNAL";
export const CREATE_MASTER_USER_INTERNAL = "CREATE_MASTER_USER_INTERNAL";
export const EDIT_MASTER_USER_INTERNAL = "EDIT_MASTER_USER_INTERNAL";

// MASTER INTERN
export const GET_ALL_MASTER_INTERN = "GET_ALL_MASTER_INTERN";
export const GET_MASTER_INTERN_BY_ID = "GET_MASTER_INTERN_BY_ID"
export const DELETE_MASTER_INTERN = "DELETE_MASTER_INTERN";
export const CREATE_MASTER_INTERN  = "CREATE_MASTER_INTERN";
export const EDIT_MASTER_INTERN  = "EDIT_MASTER_INTERN";

// MASTER ROLES
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const RE_GET_ROLES = "RE_GET_ROLES";

// MASTER ALLOWANCE
export const GET_ALL_MASTER_ALLOWANCE = "GET_ALL_MASTER_ALLOWANCE";
export const EDIT_MASTER_ALLOWANCE = "EDIT_MASTER_ALLOWANCE";

// LOGBOOK
export const GET_LOGBOOK_DATA = "GET_LOGBOOK_DATA";
export const CREATE_LOGBOOK_DATA = "SAVE_LOGBOOK_DATA";
export const EDIT_LOGBOOK_DATA = "EDIT_LOGBOOK_DATA";

//USER PROFILE
export const GET_ALL_USER_PROFILE = "GET_ALL_USER_PROFILE";
