export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const STORE_USER_ROLES = "STORE_USER_ROLES";
export const CURRENT_USER_SITE = "CURRENT_USER_SITE";

// MASTER USER
export const GET_ALL_MASTER_USER = "GET_ALL_MASTER_USER";
export const GET_MASTER_USER_BY_ID = "GET_MASTER_USER_BY_ID"
export const DELETE_MASTER_USER = "DELETE_MASTER_USER";
export const CREATE_MASTER_USER = "CREATE_MASTER_USER";
export const EDIT_MASTER_USER = "EDIT_MASTER_USER";

// MASTER ROLES
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const RE_GET_ROLES = "RE_GET_ROLES";

// MASTER AREA
export const GET_ALL_MASTER_ALLOWANCE = "GET_ALL_MASTER_ALLOWANCE";
export const EDIT_MASTER_ALLOWANCE = "EDIT_MASTER_ALLOWANCE";

// MASTER AREA
export const GET_ALL_MASTER_AREA = "GET_ALL_MASTER_AREA";
export const GET_MASTER_AREA_BY_ID = "GET_MASTER_AREA_BY_ID";
export const EDIT_MASTER_AREA = "EDIT_MASTER_AREA";

// MASTER LOKASI
export const GET_ALL_MASTER_LOKASI = "GET_ALL_MASTER_AREA";
export const GET_MASTER_LOKASI_BY_ID = "GET_MASTER_AREA_BY_ID";
export const EDIT_MASTER_LOKASI = "EDIT_MASTER_LOKASI";

//  KECELAKAAN KERJA
export const GET_ALL_KECELAKAAN_KERJA = "GET_ALL_KECELAKAAN_KERJA";
export const GET_ALL_KECELAKAAN_KERJA_BY_ID = "GET_ALL_KECELAKAAN_KERJA_BY_ID";
export const DELETE_KECELAKAAN_KERJA = "DELETE_KECELAKAAN_KERJA";
export const EDIT_KECELAKAAN_KERJA = "EDIT_KECELAKAAN_KERJA";
export const CREATE_KECELAKAAN_KERJA = "CREATE_KECELAKAAN_KERJA";

//INVENTORY
export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const GET_ALL_INVENTORY_BY_ID = "GET_ALL_INVENTORY_BY_ID";

//NEARMISS
export const GET_ALL_NEARMISS = "GET_ALL_NEARMISS";
export const GET_ALL_NEARMISS_BY_ID = "GET_ALL_NEARMISS_BY_ID";
export const CREATE_NEARMISS = "CREATE_NEARMISS";
export const DELETE_NEARMISS = "DELETE_NEARMISS";

//INSPEKSI
export const GET_ALL_INSPEKSI = "GET_ALL_INSPEKSI";
export const GET_ALL_INSPEKSI_BY_ID = "GET_ALL_INSPEKSI_BY_ID";

//USER PROFILE
export const GET_ALL_USER_PROFILE = "GET_ALL_USER_PROFILE";
