import {
  Circle,
  Grid,
  Home,
  Users,
  File,
  Map,
  MapPin,
  User,
  Box,
  List,
  HelpCircle,
  Paperclip,
  AlertTriangle,
  Compass,
  PlusSquare,
  FileText,
} from "react-feather";

export const navigationData = [
  {
    id: "home",
    title: "Home",
    icon: <Home size={24} />,
    href: "/home",
    roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-MAN", "HSSE-PIC-CAPA", "HSSE-USR"],
  },
  {
    id: "myTask",
    title: "My Task",
    icon: <List size={24} />,
    href: "/hsse/mobile/my-task",
    roles: ["HSSE-SYSADMIN", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP"],
  },
  {
    id: "hsse",
    title: "HSSE Online",
    icon: <List size={24} />,
    roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-MAN", "HSSE-PIC-CAPA", "HSSE-USR"],
    children: [
      {
        id: "master",
        title: "Master",
        icon: <Grid size={24} />,
        roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP"],
        children: [
          {
            id: "Area",
            title: "Master Area",
            icon: <Compass size={24} />,
            href: "/hsse/master/area",
            roles: ["HSSE-SU", "HSSE-SYSADMIN"],
          },
          {
            id: "Lokasi",
            title: "Master Lokasi",
            icon: <MapPin size={24} />,
            href: "/hsse/master/lokasi",
            roles: ["HSSE-SU", "HSSE-SYSADMIN"],
          },
          {
            id: "Role",
            title: "Master User",
            icon: <Users size={24} />,
            href: "/hsse/master/user",
            roles: ["HSSE-SU", "HSSE-SYSADMIN"],
          },
        ],
      },
      {
        id: "inventory",
        title: "Inventory",
        icon: <Box size={24} />,
        roles: ["HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-SU"],
        href: "/hsse/inventory",
      },
      {
        id: "kk",
        title: "Kecelakaan Kerja",
        icon: <AlertTriangle size={24} />,
        roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-MAN", "HSSE-PIC-CAPA", "HSSE-USR"],
        href: "/hsse/accident_report",
      },
      {
        id: "nms",
        title: "Nearmiss",
        icon: <List size={24} />,
        roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-MAN", "HSSE-PIC-CAPA", "HSSE-USR"],
        href: "/hsse/nearmiss",
      },
      {
        id: "p3k",
        title: "P3K",
        icon: <PlusSquare size={24} />,
        roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-MAN", "HSSE-PIC-CAPA", "HSSE-USR"],
        href: "/hsse/p3k",
      },
      {
        id: "report",
        title: "Report",
        icon: <FileText size={24} />,
        roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
        children: [
          {
            id: "Alat",
            title: "Peralatan",
            icon: <File size={24} />,
            href: "/hsse/reports/peralatan",
            roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
          },
          {
            id: "Apar",
            title: "Apar",
            icon: <File size={24} />,
            href: "/hsse/reports/apar",
            roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
          },
          {
            id: "Apd",
            title: "Apd",
            icon: <File size={24} />,
            href: "/hsse/reports/apd",
            roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
          },
          {
            id: "hdt",
            title: "Hydrant",
            icon: <File size={24} />,
            href: "/hsse/reports/hydrant",
            roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
          },
          {
            id: "ley",
            title: "Lampu Emergency",
            icon: <File size={24} />,
            href: "/hsse/reports/lampu_emergency",
            roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
          },
          {
            id: "skt",
            title: "Spill Kit",
            icon: <File size={24} />,
            href: "/hsse/reports/spillKit",
            roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
          },
          {
            id: "toa",
            title: "Toa",
            icon: <File size={24} />,
            href: "/hsse/reports/toa",
            roles: ["HSSE-SU", "HSSE-SYSADMIN", "HSSE-INSP", "HSSE-INSP-SUP", "HSSE-PIC-CAPA"],
          },
        ],
      },
    ],
  },
];
